### ISSUE TITLE
Looked at Unifi Protect at all?

### ISSUE THREAD

**Issue by staze** [project802/smartthings#8]
Would love to see this adjusted for Unifi Protect. Not sure if it's missing the hooks, or if some things just need to be shifted around. =)

**Comment by project802** [comment]
Since you need a Cloud Key Gen 2 Plus for Protect and I don't have one, I won't be able to try this out.  My understanding is the software will be an evolution of Unifi Video so hopefully the API will remain similar.  Until I can get my hands on the device or a capable user can evaluate, I won't be able to comment on support for it.
